travis:
  secure:
    BINSTAR_TOKEN: HlLVmfegLWvmwI2Hi02bhW9YrZ8eWnGx2u1NpwL6zzV07fLiyN0aZtTuxE4xfZCkyia2vgqBA4QUnFQU36NWz5USC5F8hMApctJ+gor3JcTZ8akSFTrW7pwTLQemkd95U6NVigQGWQkfsw3kp9mfOBqMmIQJNOjc8xcav7lXWbfUNzqzGICECZmYsC/BINJdSQfRA8U78RKdf/NunY/QU7yri0W544zO0egYneZNE61Jp5a4wZ0/Eci1CltjZfnLfR0TqMCa7cLcAqMLoYl9Eccjpyi7YV4zF5SbSbpf2RLYSZ0Gc0ohYt6XTFPXU/t3WHdfk6rSCnw+aCLXgkfBhdO9U5txSxU6ZacIrakUaMwqLdx7XqHi1gxLalmLE0e3M/BHxJofTtpGQvn3fIP7XJ7+KRRzIMHstBUs/GYTRM0ZfyrpkgFRtr7Sulw5epUnHwC4Jrv1yCiRfYDX4KIYHLfBFWaIDjZDBQmMP+7xE/AtLkSdwizfHDNBGOn/fkm15fZ8oXYtdT6STxL7+4Jhia3/S/VXK0usHnvowB/TyaNRsbJGdvT9Jg3HupvqcV//4ZjL6uAku5dDQ1/IvrrwAm2XJKhwvL8vkMo54u4+NkjeEetKlZxJl7T9k9WhPm9VTIboN0FwWiWlYWLWRQ8ICThoaAK4e6ezUrPsKNR15vQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
